### ISSUE TITLE
UPA provider hang, CPU high load after massive downstream disconnect/connect

### ISSUE THREAD

**Issue by ZhangLizeng** [Refinitiv/Elektron-SDK#42] opened 2017-12-14 02:19 UTC
Hi, All
We found an issue, when there are massive downstream disconnect/reconnect event. UPA provider will stop working.  We are using EMA v1.0.8

1. Further connection to UPA provider won't success.
2. Check "netstat" on server, data accumulated in receive queue.
3. Java process occupied 100% CPU core.

Below is the call stack which consumes the most CPU.

"pool-4-thread-1" #30 prio=5 os_prio=0 tid=0x00007f88e8fa8800 nid=0x489f runnable [0x00007f8879376000]
   java.lang.Thread.State: RUNNABLE
        at com.thomsonreuters.upa.transport.RsslSocketChannel$BigBuffersPool.poll(RsslSocketChannel.java:63)
        at com.thomsonreuters.upa.transport.RsslSocketChannel.acquirePair(RsslSocketChannel.java:3943)
        at com.thomsonreuters.upa.transport.ReadBufferStateMachine.acquireFragmentBuffer(ReadBufferStateMachine.java:1010)
        at com.thomsonreuters.upa.transport.ReadBufferStateMachine.processExtendedMessage(ReadBufferStateMachine.java:855)
        at com.thomsonreuters.upa.transport.ReadBufferStateMachine.updateStateCurrentLenKnown(ReadBufferStateMachine.java:496)
        at com.thomsonreuters.upa.transport.ReadBufferStateMachine.advanceOnSocketChannelRead(ReadBufferStateMachine.java:251)
        at com.thomsonreuters.upa.transport.RsslSocketChannel.performReadIO(RsslSocketChannel.java:1496)
        at com.thomsonreuters.upa.transport.RsslSocketChannel.read(RsslSocketChannel.java:1230)
        at com.thomsonreuters.upa.valueadd.reactor.Reactor.performChannelRead(Reactor.java:1712)
        at com.thomsonreuters.upa.valueadd.reactor.Reactor.dispatchAll(Reactor.java:3217)
        at com.thomsonreuters.ema.access.OmmServerBaseImpl.rsslReactorDispatchLoop(Unknown Source)
        at com.thomsonreuters.ema.access.OmmServerBaseImpl.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ZhangLizeng** [comment] 2017-12-15 01:21
[EmaConfig.xml.txt](https://github.com/thomsonreuters/Elektron-SDK/files/1561290/EmaConfig.xml.txt)
Hi, Sebastian
Thank you for help on this.   

Sorry for making confusion, I use EMA (Elektron-SDK) directly, but as I know UPA is the transport libary for EMA? Maybe UPA provider in my concept is EMA provider.   

My provider connected to a consumer application.

Attached the EmaConfig, please note that my application is also a EMA consumer connected to HMDS, so there are configuration for both consumer and provider. Issue is in provider part.

My application is multi-threaded. 

Thank you.

**Comment by bberner** [comment] 2018-08-22 15:54
We have been unable to reproduce this problem. Could you please see if the problem is still occurring in the most recent release (1.2.1)? You said you saw the issue in version 1.0.8. Several multi-threaded problems have been fixed between version 1.0.8 and version 1.2.1.

**Comment by vlevendel** [comment] 2019-01-07 20:57
@clear-m Please open a separate issue with stack trace for the C++ problem with details on how to reproduce the issue.

**Comment by vlevendel** [comment] 2019-04-15 21:39
@ZhangLizeng Is this still an issue with ESDK Java?

**Comment by vlevendel** [comment] 2019-04-22 19:34
@ZhangLizeng Closing for now.  Please reopen if this occurs with latest code.

**Closed by vlevendel** 2019-04-22 19:34 UTC
