### ISSUE TITLE
Java Elektron SDK-1.5.0: race conditions parsing dictionary

### ISSUE THREAD

**Issue by mehappycamper** [Refinitiv/Elektron-SDK#141] opened 2020-05-08 22:10 UTC
Hello Refinitiv, @<zoya.farberov@refinitiv.com>

Here is what I see:

I receive an Image/Refresh and then process a message using Refinitiv-supplied JSON rendering from Refinitiv examples. When I'm doing that synchronously, everything is fine. But if I'm doing it asynchronously (just adding a message to the queue and processing it in a separate thread), then I'm getting an exception below.

The issue I experience is caused by race conditions, most likely, in the com.thomsonreuters.ema.access.DictionaryEntryImpl code. The code shares the static Dictionary object between multiple messages and can't properly parse the dictionary if the messages come in in a rapid succession. If I give the Dispatcher at least 5 additional millisecond to process a message, it works as it should.

Synchronizing the processing in this case doesn't help because the dictionary object is shared by the API between multiple messages, and I don't have access to it. For the same reason, deep cloning of the messages doesn't work, either.

I do realize that a workaround exists which is to deep-clone a message synchronously and then to process the cloned message asynchronously but I still think that a cleaner solution would be to resolve the issue on the Elektron API level.

What I see is very similar to the already reported problem 
 https://github.com/Refinitiv/Elektron-SDK/issues/136.

This is ***NOT*** a client application issue as Refinitiv suggests in #136, this is a thread safety issue in the Elektron SDK.

The code snippet (the dispatcher is in the middle of processing about 400 requests):

`private MarketPrice createMarkePrice(OmmConsumer consumer, String ric) {
	MarketPrice.OnImageFunction processImage = (marketPrice, fields, state) -> {
		logger.debug("\r\n{}: New Image/Refresh received, state {}", ric, state);
		process(ric, fields);
		// If I sleep here for 5 msec, everything is OK
	};

	MarketPrice theMarketPrice = new MarketPrice.Builder().withOmmConsumer(consumer).withName(ric)
			.withServiceName(refinitivServiceName).withUpdates(withUpdates).onImage(processImage)
			.build();
	return theMarketPrice;
}

private void process(String ric, Collection<Field> fields) {
	QueueWrapper qr = new QueueWrapper(ric, fields);
	// just adding to a queue
	dataQueue.add(qr);
	logger.debug("{}: added to dataQueue, now have {}", ric, dataQueue.size());
}

	/**
	 * Dispatch events until the <code>MarkePrice</code> is complete.
	 * 
	 * @param marketPrice the <code>MarkePrice</code>
	 */
	private void dispatchSnapshotEvent(Completable c) {
		try {
			dispatcher.dispatchEventsUntilComplete(c);
		} catch (Exception e) {
			// Exception is caught here!!!
			logger.error("ERROR - snapshot event dispatching failed", e);
		}
	}
`
I'm attaching the complete code that could help reproduce the problem, Here is an example of the actual exception, and I'm getting exceptions for random fields and values which tells me that this is a race condition:

com.thomsonreuters.ema.access.OmmInvalidUsageExceptionImpl: The enum value 40 for the Field ID 11 does not exist in enumerated type definitions
	at 

com.thomsonreuters.ema.access.DataDictionaryImpl.ommIUExcept(DataDictionaryImpl.java:1057) ~[ema-3.5.0.0.jar:emaj3.5.0.L1.all.rrg]
	at com.thomsonreuters.ema.access.DataDictionaryImpl.enumType(DataDictionaryImpl.java:870) ~[ema-3.5.0.0.jar:emaj3.5.0.L1.all.rrg]

[refinitiv.zip](https://github.com/Refinitiv/Elektron-SDK/files/4601943/refinitiv.zip)
[config.zip](https://github.com/Refinitiv/Elektron-SDK/files/4602336/config.zip)

**Comment by IProkopenkoRef** [comment] 2020-05-19 09:44
Hi @mehappycamper
Sorry for your challenges using this API and thank you for code attached. Unfortunately issue was not reproduced nor using your example neither its modification with several additional polling threads being added.

From the original exception: lookup was performed on Field ID 11 value 40, however FID 11 is not defined as an enumerated field, see RDMFieldDictionar.
> `com.thomsonreuters.ema.access.OmmInvalidUsageExceptionImpl: The enum value 40 for the  does not exist in enumerated type definitions`

Please check application is using proper dictionary and enum definition. Based on configuration dictionary could be supplied by provider application.

EMAJ DataDictionaryImpl is thread-safe since ESDK 1.5.0 - ReentrantLock was introduced. So most likely original message was distorted by subsequent message and polling thread works with the corrupted message.
Additional information is required to continue investigation

@mehappycamper,
1. What is the request/response rate you can see in application? How many requests/responses application handles in a second? What is the average latency between received data snapshots?
2. Please provide EmaConfig.xml, full stacktrace. Full application logs also would be helpful.

**Comment by mehappycamper** [comment] 2020-05-29 17:14
Hi @IProkopenkoRef, sorry for the delayed response.

Looking at my XML config, I'm using the online Dictionary, so it should be always up-to-date.

Request/response rate is not huge, not greater than 10 messages per second. Latency is minimal. The issue manifests itself immediately, as soon as I start sending requests.

I'll prepare a project based on the bare bones **MarketPriceSubscriber** from Refinitiv so you should be able to easily reproduce the issue.

Meanwhile, if you have the opportunity, you may want to take a look at what's going on in **printInJsonFormat(MarketPrice marketPrice, String eventType, Collection<Field> fields)**, I'm pretty sure the problem is there.

Regards

**Comment by vlevendel** [comment] 2020-06-30 20:52
This is addressed with 1.5.0.G1.  Please let us know if you have further questions.  Closing.

**Closed by vlevendel** 2020-06-30 20:52 UTC
